# PyTorch elementals

Based on [this page](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

First, construct uninitialized matrix

In [5]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)
print(x)

tensor([[-2.0536e-13,  3.0674e-41,  4.4842e-44],
        [ 0.0000e+00,         nan,  2.0192e-19],
        [ 5.2664e-08,  5.3408e-08,  1.0791e-08],
        [ 1.0489e-08,  4.3680e-05,  8.4713e-07],
        [ 4.2233e-08,  1.3075e+22,  6.4641e-04]])


A random matrix

In [6]:
x = torch.rand(5, 3)

x

tensor([[0.2359, 0.1708, 0.4211],
        [0.3184, 0.7494, 0.6653],
        [0.3741, 0.4812, 0.2599],
        [0.0403, 0.1975, 0.1705],
        [0.3704, 0.5414, 0.8273]])

Or directly from data

In [9]:
x = torch.tensor([
    [1, 0, 0.001],
    [0, 1, 0.001],
    [0.001, 0, 1],
])

x

tensor([[1.0000, 0.0000, 0.0010],
        [0.0000, 1.0000, 0.0010],
        [0.0010, 0.0000, 1.0000]])

Converting to numpy

In [10]:
x.numpy()

array([[1.   , 0.   , 0.001],
       [0.   , 1.   , 0.001],
       [0.001, 0.   , 1.   ]], dtype=float32)

Numpy -> Torch

## Cuda



In [12]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!